# server配置
server:
  port: 8194
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /reportdata

# spring配置
spring:
  profiles:
    active: prod
  application:
    name: report-data
  cloud:
    nacos:
      config:
        server-addr: 192.168.1.128:8848
        file-extension: yaml
      discovery:
        server-addr: 192.168.1.128:8848
        enabled: true
        namespace: prod

  # 数据库配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.70:5432/jiudingxuan
    username: gpadmin
    password: gp1QAZ1234
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 8
    tomcat:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    database: 3
    host: 192.168.1.127
    port: 6379
    password: Redis1234!@#$
    # 使用连接池
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        min-idle: 0
  rabbitmq:
    host: njwd.tpddns.cn
    port: 16072
    username: guest
    password: guest
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8
    serialization:
      # false:不使用 true:使用 时间戳
      write-dates-as-timestamps: true


logging:
  config: classpath:logback.xml

mybatis-plus:
  mapper-locations: classpath*:/com/njwd/**/mapper/**/*.xml
  typeAliasesPackage: com.njwd.*.entity
  configLocation: classpath:/mybatis-config.xml
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_null
      table-prefix: wd_
  type-handlers-package: com.njwd.handler

#自定义常量
constant:
  file:
    #服务端excel的保存路径,模版在该路径下,上传的excle文件在对应文件夹下
    excelRootPath: /home/middle_end/excel_upload/

#kettle文件库
kettle:
  script:
    path: /home/zhongtai/kettle
    propertiesFilePath: /home/zhongtai/kettle

#swagger
swagger:
  enable: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

#openfire地址
#openfire:
#  server: 192.168.1.215
#  domainName: njwdopenfire
#  port: 5222
#  #配置用发送消息的账号信息
#  loginAccount: admin
#  loginPassword: admin
#统一认证登录跳转地址配置
zhongtai:
  ssoUrl: http://www.zhenjiangruoxiangyu.cn:180/sso/authentication/getLoginUserInfoByToken
  redirectAdminUrl: http://jdx.zhenjiangruoxiangyu.cn:8000/middle-data-admin/
  redirectReportUrl: http://jdx.zhenjiangruoxiangyu.cn:8000/middle-data-frontend/