# server配置
server:
  port: 8194
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /reportdata

# spring配置
spring:
  profiles:
    active: test
  application:
    name: report-data
  cloud:
    nacos:
      config:
        server-addr: 10.16.1.234:8848
        file-extension: yaml
      #namespace:
      discovery:
        server-addr: 10.16.1.234:8848
        enabled: true
        namespace: test

  # 数据库配置
  # 数据库配置
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://njwd.tpddns.cn:15432/jiudingxuan_test
    username: gpadmin
    password: gpadmin
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 50
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password: redis123!@#
    # 使用连接池
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        min-idle: 0
  rabbitmq:
    host: njwd.tpddns.cn
    port: 16072
    username: guest
    password: guest
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8
    serialization:
      # false:不使用 true:使用 时间戳
      write-dates-as-timestamps: true


logging:
  config: classpath:logback.xml

mybatis-plus:
  mapper-locations: classpath*:/com/njwd/**/mapper/**/*.xml
  typeAliasesPackage: com.njwd.*.entity
  configLocation: classpath:/mybatis-config.xml
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_null
      table-prefix: wd_
  type-handlers-package: com.njwd.handler

#自定义常量
constant:
  file:
    #服务端excel的保存路径,模版在该路径下,上传的excle文件在对应文件夹下
    excelRootPath: /home/middle_end/excel_upload/

#kettle文件库
kettle:
  script:
    path: /home/zhongtai/kettle
    propertiesFilePath: /home/zhongtai/kettle

#swagger
swagger:
  enable: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

#openfire地址
#openfire:
#  server: 192.168.1.215
#  domainName: njwdopenfire
#  port: 5222
#  #配置用发送消息的账号信息
#  loginAccount: admin
#  loginPassword: admin
#统一认证登录跳转地址配置
zhongtai:
#  ssoUrl: http://10.16.1.234/sso/authentication/getLoginUserInfoByToken
#  redirectAdminUrl: http://10.16.1.234/middle-data-admin
#  redirectReportUrl: http://10.16.1.234/middle-data-frontend
  ssoUrl: http://njwd.tpddns.cn:8191/sso/authentication/getLoginUserInfoByToken
  redirectAdminUrl: http://njwd.tpddns.cn:8191/middle-data-admin
  redirectReportUrl: http://njwd.tpddns.cn:8191/middle-data-frontend