# server配置
server:
  port: 8192
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /schedule

# spring配置
spring:
  profiles:
    active: dev
  application:
    name: schedule
  cloud:
    nacos:
      config:
        server-addr: 116.62.148.189:8848
        file-extension: yaml
      #        namespace:
      discovery:
        server-addr: 116.62.148.189:8848
        enabled: true
        namespace: libao

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://mzdp8888.mysql.rds.aliyuncs.com:3306/middle_db?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
#    username: zt_develop
#    password: ZhongTai8888
    url: jdbc:mysql://10.16.1.237:3306/middle_db?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: admin
    password: admin1245!@$%
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 8
    tomcat:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    database: 4
    host: 10.16.1.235
    port: 6379
    password: redis123!@#
    # 使用连接池
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        min-idle: 0
  rabbitmq:
    host: 10.16.1.160
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true    #  消息发送到交换机确认机制,是否确认回调
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timezone: GMT+8
    serialization:
      # false:不使用 true:使用 时间戳
      write-dates-as-timestamps: true


logging:
  config: classpath:logback.xml

mybatis-plus:
  mapper-locations:  classpath*:/com/njwd/**/mapper/**/*.xml
  #mapper-locations: classpath:META-INF/**/mapper/*Mapper.xml
  typeAliasesPackage: com.njwd.*.entity
  global-config:
    db-config:
      id-type: uuid
      field-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-handlers-package: com.njwd.handler



#kettle文件库
kettle:
  script:
    path: D:\KTR\ktr

#自定义常量
constant:
  file:
    #服务端excel的保存路径,模版在该路径下,上传的excle文件在对应文件夹下
    excelRootPath: /home/middle_end/excel_upload/

swagger:
  enable: true

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
#openfire地址
#openfire:
#  server: 192.168.1.215
#  domainName: njwdopenfire
#  port: 5222
#  #配置用发送消息的账号信息
#  loginAccount: admin
#  loginPassword: admin
#系统参数
